# Shows the "Sponsor" button on the GitHub repository page.
github: rimaturus
# Other options, if you use them: ko_fi: <name>, buy_me_a_coffee: <name>, liberapay: <name>, custom: ["https://paypal.me/<name>"]
