#!/bin/sh
# Builds PhotoVault without Gradle: aapt/aapt2 + javac + dx, then an APK (zipalign + apksigner) or an App Bundle (bundletool).
#   Ubuntu 24.04:  sudo apt install aapt apksigner dalvik-exchange zipalign openjdk-21-jdk-headless zip unzip curl
#   Termux (Android, .aab only):  pkg install git openjdk-21 aapt aapt2 d8 zip unzip curl
#   KS_PASS=... ./build.sh                 PhotoVault.apk, GitHub build (with the donation link)
#   KS_PASS=... PLAY=1 ./build.sh          PhotoVault-play.apk, Google Play texts (no donation link: Play's payments policy)
#   KS_PASS=... PLAY=1 AAB=1 ./build.sh    PhotoVault-play.aab for Google Play: App Bundle with code transparency
#   ONEDRIVE_CLIENT_ID=... GOOGLE_CLIENT_ID=... KS_PASS=... ./build.sh   with OneDrive / Google Drive (your app registrations)
set -e
cd "$(dirname "$0")"
# Donation link shown in the app (Settings > Support PhotoVault). Empty = no donation button.
DONATE_URL="${DONATE_URL-https://buymeacoffee.com/rimaturus}"
SOURCE_URL="${SOURCE_URL-https://github.com/rimaturus/CloakRoll}"
# OneDrive: the "Application (client) ID" of your Microsoft app registration (PUBLISHING.md). Empty = OneDrive not offered.
ONEDRIVE_CLIENT_ID="${ONEDRIVE_CLIENT_ID-}"
# Google Drive: the "Client ID" of your Google OAuth client, type iOS (PUBLISHING.md). Empty = Google Drive not offered.
GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID-806356058259-0f19gg4o54pvvl0v2rkoo5tq91376g5h.apps.googleusercontent.com}"
# Google Play: no donation link and no link to a page with donation links (Play payments policy, see PUBLISHING.md)
[ "$PLAY" = 1 ] && DONATE_URL="" && SOURCE_URL=""
# Java compiles against API 36; resources are linked against API 34 because Debian's aapt can't read newer
# framework resource tables (the framework attribute IDs used here are identical in both).
JAR=sdk/android-36.jar RES_JAR=sdk/android-34.jar BUNDLETOOL=sdk/bundletool-all-1.18.3.jar
mkdir -p sdk
# Every download comes from Google and is checked against a pinned SHA-256, on every build.
fetch() { # <file> <sha256> <url> [path inside the zip]
    echo "$2  $1" | sha256sum -c --status - 2>/dev/null && return
    rm -f "$1"; curl -fsSL -o "$1.dl" "$3"
    if [ -n "$4" ]; then unzip -p "$1.dl" "$4" > "$1"; rm "$1.dl"; else mv "$1.dl" "$1"; fi
    echo "$2  $1" | sha256sum -c --status - || { rm -f "$1"; echo "$1: SHA-256 mismatch, refused"; exit 1; }
}
fetch "$JAR" d9eb9da824d9e247a352f570f01e1169e725b2954bca9e283a71786c59b59f9a \
    https://dl.google.com/android/repository/platform-36_r02.zip android-36/android.jar
fetch "$RES_JAR" 6cea1df3efb77103ac3e2beb9bf4718964b0e0869ab16d39d29d5cbae1c147ad \
    https://dl.google.com/android/repository/platform-34-ext7_r03.zip android-34/android.jar
[ "$AAB" != 1 ] || fetch "$BUNDLETOOL" a099cfa1543f55593bc2ed16a70a7c67fe54b1747bb7301f37fdfd6d91028e29 \
    https://github.com/google/bundletool/releases/download/1.18.3/bundletool-all-1.18.3.jar
KEYSTORE="${KEYSTORE-photovault.jks}"
[ -n "$KS_PASS" ] || { echo "Set KS_PASS to the signing-key password (README > Build from source)."; exit 1; }
rm -rf build && mkdir -p build/classes build/gen/app/photovault res/raw
cp PRIVACY.md res/raw/privacy.txt # the privacy policy, shown inside the app
cat > build/gen/app/photovault/Config.java <<EOC
package app.photovault;
/** Generated by build.sh */
final class Config {
    static final String DONATE_URL = "$DONATE_URL";
    static final String SOURCE_URL = "$SOURCE_URL";
    static final String ONEDRIVE_CLIENT_ID = "$ONEDRIVE_CLIENT_ID";
    static final String GOOGLE_CLIENT_ID = "$GOOGLE_CLIENT_ID";
}
EOC
# resources: texts in 6 languages; R.java is generated for the Java package app.photovault
if [ "$AAB" = 1 ]; then # App Bundle: resources in aapt2's protobuf format
    aapt2 compile --dir res -o build/res.zip
    aapt2 link --proto-format -o build/res.apk -I "$RES_JAR" --manifest AndroidManifest.xml --java build/gen --custom-package app.photovault build/res.zip
else
    aapt package -f -0 arsc -M AndroidManifest.xml -S res -I "$RES_JAR" -F build/res.apk -J build/gen --custom-package app.photovault
fi
javac -nowarn -Xlint:-options -source 8 -target 8 -bootclasspath "$JAR" -d build/classes $(find src build/gen -name '*.java')
if command -v dalvik-exchange >/dev/null; then
    dalvik-exchange --dex --min-sdk-version=26 --output=build/classes.dex build/classes
else # Termux: d8 instead of Debian's dx
    jar cf build/classes.jar -C build/classes . && d8 --release --min-api 33 --lib "$JAR" --output build build/classes.jar
fi
[ -f "$KEYSTORE" ] || keytool -genkeypair -keystore "$KEYSTORE" -storepass "$KS_PASS" -keypass "$KS_PASS" \
    -alias photovault -keyalg RSA -keysize 4096 -validity 10000 -dname "CN=PhotoVault"
# Signing: keep the keystore private and out of git. Anyone with it can publish "updates" that install over your users' app.

if [ "$AAB" = 1 ]; then
    # base module layout: manifest/, dex/, res/, resources.pb
    mkdir -p build/base/manifest build/base/dex
    (cd build/base && unzip -q ../res.apk && mv AndroidManifest.xml manifest/ && cp ../classes.dex dex/ && zip -qr ../base.zip .)
    java -jar "$BUNDLETOOL" build-bundle --modules=build/base.zip --output=build/plain.aab
    # code transparency: a signed list of the code, so anyone can check that what Play installs is exactly this build
    (umask 077; printf '%s\n' "$KS_PASS" > build/ks.pass)
    java -jar "$BUNDLETOOL" add-transparency --bundle=build/plain.aab --output=build/transparent.aab \
        --ks="$KEYSTORE" --ks-key-alias=photovault --ks-pass=file:build/ks.pass
    rm -f build/ks.pass
    OUT=PhotoVault-play.aab; [ "$PLAY" = 1 ] || OUT=PhotoVault.aab
    # the bundle is signed with the upload key; Google Play re-signs the APKs it delivers (Play App Signing)
    jarsigner -keystore "$KEYSTORE" -storepass:env KS_PASS -sigalg SHA256withRSA -digestalg SHA-256 \
        -signedjar "$OUT" build/transparent.aab photovault > /dev/null
    jarsigner -verify "$OUT" | head -1
    keytool -printcert -jarfile "$OUT" | grep SHA256
else
    cp build/res.apk build/unsigned.apk
    (cd build && zip -q unsigned.apk classes.dex)
    zipalign -f -p 4 build/unsigned.apk build/aligned.apk
    OUT=PhotoVault.apk; [ "$PLAY" = 1 ] && OUT=PhotoVault-play.apk
    apksigner sign --v2-signing-enabled true --v3-signing-enabled true --ks "$KEYSTORE" --ks-pass env:KS_PASS \
        --ks-key-alias photovault --out "$OUT" build/aligned.apk
    apksigner verify --print-certs "$OUT" | grep SHA-256
fi
echo "OK: $OUT  sha256 $(sha256sum "$OUT" | cut -d' ' -f1)"
