#!/bin/sh
# Builds PhotoVault.apk without Gradle: aapt + javac + dx + zipalign + apksigner.
#   Ubuntu 24.04:  sudo apt install aapt apksigner dalvik-exchange zipalign openjdk-21-jdk-headless zip curl
#   KS_PASS=... ./build.sh           GitHub build (with the donation link)
#   KS_PASS=... PLAY=1 ./build.sh    Google Play build (no donation link: Play's payments policy)
#   ONEDRIVE_CLIENT_ID=... KS_PASS=... ./build.sh   with OneDrive (needs your Microsoft app registration)
set -e
cd "$(dirname "$0")"
# Donation link shown in the app (Info and Menu > Support PhotoVault). Empty = no donation button.
DONATE_URL="${DONATE_URL-https://buymeacoffee.com/rimaturus}"
SOURCE_URL="${SOURCE_URL-https://github.com/rimaturus/PhotoVault}"
# OneDrive: the "Application (client) ID" of your Microsoft app registration (PUBLISHING.md). Empty = OneDrive not offered.
ONEDRIVE_CLIENT_ID="${ONEDRIVE_CLIENT_ID-}"
# Google Play: no donation link and no link to a page with donation links (Play payments policy, see PUBLISHING.md)
[ "$PLAY" = 1 ] && DONATE_URL="" && SOURCE_URL=""
# Java compiles against API 36; resources are linked against API 34 because Debian's aapt can't read newer
# framework resource tables (the framework attribute IDs used here are identical in both).
JAR=sdk/android-36.jar RES_JAR=sdk/android-34.jar
mkdir -p sdk
[ -f "$JAR" ] || curl -sSL -o "$JAR" https://raw.githubusercontent.com/Reginer/aosp-android-jar/main/android-36/android.jar
[ -f "$RES_JAR" ] || curl -sSL -o "$RES_JAR" https://raw.githubusercontent.com/Reginer/aosp-android-jar/main/android-34/android.jar
rm -rf build && mkdir -p build/classes build/gen/app/photovault
cat > build/gen/app/photovault/Config.java <<EOC
package app.photovault;
/** Generated by build.sh */
final class Config {
    static final String DONATE_URL = "$DONATE_URL";
    static final String SOURCE_URL = "$SOURCE_URL";
    static final String ONEDRIVE_CLIENT_ID = "$ONEDRIVE_CLIENT_ID";
}
EOC
# resources: texts in 6 languages; R.java is generated for the Java package app.photovault
aapt package -f -0 arsc -M AndroidManifest.xml -S res -I "$RES_JAR" -F build/res.apk -J build/gen --custom-package app.photovault
javac -nowarn -Xlint:-options -source 8 -target 8 -bootclasspath "$JAR" -d build/classes $(find src build/gen -name '*.java')
dalvik-exchange --dex --min-sdk-version=26 --output=build/classes.dex build/classes
cp build/res.apk build/unsigned.apk
(cd build && zip -q unsigned.apk classes.dex)
zipalign -f -p 4 build/unsigned.apk build/aligned.apk
# Signing: keep the keystore private and out of git. Anyone with it can publish "updates" that install over your users' app.
KEYSTORE="${KEYSTORE-photovault.jks}"
[ -n "$KS_PASS" ] || { echo "Set KS_PASS to the signing-key password (README → Build from source)."; exit 1; }
[ -f "$KEYSTORE" ] || keytool -genkeypair -keystore "$KEYSTORE" -storepass "$KS_PASS" -keypass "$KS_PASS" \
    -alias photovault -keyalg RSA -keysize 4096 -validity 10000 -dname "CN=PhotoVault"
OUT=PhotoVault.apk; [ "$PLAY" = 1 ] && OUT=PhotoVault-play.apk
apksigner sign --v2-signing-enabled true --v3-signing-enabled true --ks "$KEYSTORE" --ks-pass env:KS_PASS \
    --ks-key-alias photovault --out "$OUT" build/aligned.apk
apksigner verify --print-certs "$OUT" | grep SHA-256
echo "OK: $OUT  sha256 $(sha256sum "$OUT" | cut -d' ' -f1)"
