#!/bin/sh
# build.sh for Windows (Git Bash) with Android Studio's JDK and the SDK's build-tools: aapt2 + javac + d8, then an APK
# (zipalign + apksigner) or an App Bundle (bundletool). Same options as build.sh:
#   KS_PASS=... ./build-win.sh                 Cloakroll.apk, GitHub build (with the donation link)
#   KS_PASS=... PLAY=1 ./build-win.sh          Cloakroll-play.apk, Google Play texts (no donation link)
#   KS_PASS=... PLAY=1 AAB=1 ./build-win.sh    Cloakroll-play.aab for Google Play, with code transparency
#   ONEDRIVE_CLIENT_ID=... GOOGLE_CLIENT_ID=... KS_PASS=... ./build-win.sh   with OneDrive / Google Drive
# Paths below: change if your Android Studio or SDK is elsewhere.
set -e
cd "$(dirname "$0")"
JBIN="${JBIN-/c/Program Files/Android/Android Studio/jbr/bin}"
SDK="${ANDROID_SDK-$LOCALAPPDATA/Android/Sdk}"
BT="$SDK/build-tools/${BUILD_TOOLS-35.0.0}"
JAR="$SDK/platforms/android-36/android.jar"
export JAVA_HOME="$(cygpath -w "$(dirname "$JBIN")")" # d8.bat and apksigner.bat look for it
BUNDLETOOL=sdk/bundletool-all-1.18.3.jar
DONATE_URL="${DONATE_URL-https://buymeacoffee.com/rimaturus}"
SOURCE_URL="${SOURCE_URL-https://github.com/rimaturus/CloakRoll}"
ONEDRIVE_CLIENT_ID="${ONEDRIVE_CLIENT_ID-}"
GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID-806356058259-0f19gg4o54pvvl0v2rkoo5tq91376g5h.apps.googleusercontent.com}"
[ "$PLAY" = 1 ] && DONATE_URL="" && SOURCE_URL=""
KEYSTORE="${KEYSTORE-photovault.jks}"
[ -n "$KS_PASS" ] || { echo "Set KS_PASS to the signing-key password (README > Build from source)."; exit 1; }
[ -f "$JAR" ] || { echo "Android SDK platform 36 not found at $JAR"; exit 1; }
w() { cygpath -w "$1"; }
mkdir -p sdk
[ "$AAB" != 1 ] || [ -f "$BUNDLETOOL" ] || curl -sSL -o "$BUNDLETOOL" https://github.com/google/bundletool/releases/download/1.18.3/bundletool-all-1.18.3.jar
rm -rf build && mkdir -p build/classes build/gen/app/photovault res/raw
cp PRIVACY.md res/raw/privacy.txt # the privacy policy, shown inside the app
cat > build/gen/app/photovault/Config.java <<EOC
package app.photovault;
/** Generated by build-win.sh */
final class Config {
    static final String DONATE_URL = "$DONATE_URL";
    static final String SOURCE_URL = "$SOURCE_URL";
    static final String ONEDRIVE_CLIENT_ID = "$ONEDRIVE_CLIENT_ID";
    static final String GOOGLE_CLIENT_ID = "$GOOGLE_CLIENT_ID";
}
EOC
"$BT/aapt2.exe" compile --dir res -o "$(w build/res.zip)"
if [ "$AAB" = 1 ]; then
    "$BT/aapt2.exe" link --proto-format -o "$(w build/res.apk)" -I "$(w "$JAR")" --manifest AndroidManifest.xml --java "$(w build/gen)" --custom-package app.photovault "$(w build/res.zip)"
else
    "$BT/aapt2.exe" link -o "$(w build/res.apk)" -I "$(w "$JAR")" --manifest AndroidManifest.xml --java "$(w build/gen)" --custom-package app.photovault "$(w build/res.zip)"
fi
"$JBIN/javac.exe" -nowarn -Xlint:-options -source 8 -target 8 -bootclasspath "$(w "$JAR")" -d "$(w build/classes)" $(find src build/gen -name '*.java')
"$JBIN/jar.exe" cf build/classes.jar -C build/classes .
"$BT/d8.bat" --release --min-api 33 --lib "$(w "$JAR")" --output "$(w build)" "$(w build/classes.jar)"
[ -f "$KEYSTORE" ] || "$JBIN/keytool.exe" -genkeypair -keystore "$KEYSTORE" -storepass "$KS_PASS" -keypass "$KS_PASS" \
    -alias photovault -keyalg RSA -keysize 4096 -validity 10000 -dname "CN=PhotoVault"

if [ "$AAB" = 1 ]; then
    mkdir -p build/base/manifest build/base/dex
    (cd build/base && unzip -q ../res.apk && mv AndroidManifest.xml manifest/ && cp ../classes.dex dex/ && zip -qr ../base.zip .)
    "$JBIN/java.exe" -jar "$BUNDLETOOL" build-bundle --modules="$(w build/base.zip)" --output="$(w build/plain.aab)"
    (umask 077; printf '%s\n' "$KS_PASS" > build/ks.pass)
    "$JBIN/java.exe" -jar "$BUNDLETOOL" add-transparency --bundle="$(w build/plain.aab)" --output="$(w build/transparent.aab)" \
        --ks="$(w "$KEYSTORE")" --ks-key-alias=photovault --ks-pass="file:$(w build/ks.pass)"
    rm -f build/ks.pass
    OUT=Cloakroll-play.aab; [ "$PLAY" = 1 ] || OUT=Cloakroll.aab
    "$JBIN/jarsigner.exe" -keystore "$KEYSTORE" -storepass:env KS_PASS -sigalg SHA256withRSA -digestalg SHA-256 \
        -signedjar "$OUT" build/transparent.aab photovault > /dev/null
    "$JBIN/jarsigner.exe" -verify "$OUT" | head -1
    "$JBIN/keytool.exe" -printcert -jarfile "$OUT" | grep SHA256
else
    cp build/res.apk build/unsigned.apk
    (cd build && zip -q unsigned.apk classes.dex)
    "$BT/zipalign.exe" -f -p 4 build/unsigned.apk build/aligned.apk
    OUT=Cloakroll.apk; [ "$PLAY" = 1 ] && OUT=Cloakroll-play.apk
    "$BT/apksigner.bat" sign --v2-signing-enabled true --v3-signing-enabled true --ks "$(w "$KEYSTORE")" --ks-pass env:KS_PASS \
        --ks-key-alias photovault --out "$OUT" build/aligned.apk
    "$BT/apksigner.bat" verify --print-certs "$OUT" | grep SHA-256
fi
echo "OK: $OUT  sha256 $(sha256sum "$OUT" | cut -d' ' -f1)"
